name: ✅Lint Status Check
run-name: ✅Lint Status Check (${{ github.base_ref }} branch)


defaults:
  run:
    shell: pwsh


on:
  pull_request:
    branches: [main, preview]


jobs:
  lint_status_check:
    name: Lint Status Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Set Up Deno (${{ vars.DENO_VERSION }})
      uses: denoland/setup-deno@v2
      with:
        deno-version: ${{ vars.DENO_VERSION }}
        cache: true

    - name: Run Lint
      run: deno lint **/*/*.ts;
